# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l4YKAOjYIb6GwCNtMcSUprVb5qdm9ukN

Programa que sume dos numeros
"""

#Leer 2 número y mostral la suma
a = int (input("Ingrese el primer numero"))
b = int (input("Ingrese el segundo numero"))
suma = a + b
print ("la suma es", suma)

edad = int(input("Ingrese la edad de la persona "))
if edad >= 18:
 mje ="Es mayor de edad"
else:
 mje ="Es menor de edad"
print(mje)

"""Promediar Notas

"""

# Programa para calcular el promedio de 3 notas

# Entrada de datos
nota1 = float(input("Ingrese la primera nota: "))
nota2 = float(input("Ingrese la segunda nota: "))
nota3 = float(input("Ingrese la tercera nota: "))

# Cálculo del promedio
promedio = (nota1 + nota2 + nota3) / 3

# Mostrar el resultado
print(f"\nEl promedio es: {promedio:.2f}")

# Verificar si aprobó o no
if promedio >= 11:
    print("Aprobaste")
else:
    print("No Aprobaste")
1

nota1 = float(input("Ingrese la primera nota: "))
nota2 = float(input("Ingrese la segunda nota: "))
nota3 = float(input("Ingrese la tercera nota: "))
promedio = (nota1 + nota2 + nota3) / 3
print(f"/El promedio es; {promedio:.2f}" )
if promedio >=11:
  print("Aprobaste")
else:
  print("No Aprobaste")